services:
  es8:
    image: elasticsearch:8.13.4
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kib8:
    image: kibana:8.13.4
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
    ports:
    - 5601:5601
    networks:
      - elastic
    depends_on:
      - es8
  nginx:
    image: nginx
    container_name: nginx_store
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_docker/nginx/logs:/var/log/nginx/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    ports:
      - 8080:80
    working_dir: /etc/nginx/
    depends_on:
      - phpmyadmin
      - php
    networks:
      - elastic
  db:
    image: mariadb
    container_name: db_store
    environment:
      MARIADB_USER: 1
      MARIADB_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: 123
    volumes:
      - ./_docker/database:/var/lib/mysql
      networks:
      - elastic
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_store
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - elastic
  php:
    container_name: php_store
    build: ./_docker/build/php/
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker

    networks:
      - elastic


networks:
  elastic:
    name: elastic
